# Generated by Django 3.1 on 2020-08-14 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songapp', '0002_auto_20200814_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='image',
        ),
    ]
